const cars = [
  {
    id: 1,
    brand: "Toyota",
    model: "Camry",
    price: "₹41,70,000",
    fuel: "Petrol",
    seats: 5,
    year: 2022,
    mileage: "14 kmpl",
    description: "A stylish and premium sedan with a smooth driving experience.",
    image: "/images/camry.jpg",
    link: "https://www.toyotabharat.com/showroom/camry/"
  },
  {
    id: 2,
    brand: "Hyundai",
    model: "Creta",
    price: "₹13,45,000",
    fuel: "Diesel",
    seats: 5,
    year: 2023,
    mileage: "18 kmpl",
    description: "A compact SUV known for comfort, looks, and tech features.",
    image: "/images/creta.jpg",
    link: "https://www.hyundai.com/in/en/find-a-car/creta/highlights"
  },
  {
    id: 3,
    brand: "Maruti Suzuki",
    model: "Swift",
    price: "₹6,99,000",
    fuel: "Petrol",
    seats: 5,
    year: 2022,
    mileage: "21 kmpl",
    description: "A reliable hatchback ideal for city drives and fuel efficiency.",
    image: "/images/swift.jpg",
    link: "https://www.marutisuzuki.com/swift"
  },
  {
    id: 4,
    brand: "Tata",
    model: "Nexon EV",
    price: "₹14,49,000",
    fuel: "Electric",
    seats: 5,
    year: 2023,
    mileage: "312 km/full charge",
    description: "One of the best electric SUVs in India with modern tech.",
    image: "/images/nexon-ev.avif",
    link: "https://ev.tatamotors.com/suv/nexon-ev"
  },
  {
    id: 5,
    brand: "Mahindra",
    model: "Thar",
    price: "₹15,49,000",
    fuel: "Diesel",
    seats: 4,
    year: 2023,
    mileage: "15 kmpl",
    description: "A rugged off-roader that combines power with modern appeal.",
    image: "/images/thar.jpg",
    link: "https://auto.mahindra.com/suv/thar"
  },
  {
    id: 6,
    brand: "Kia",
    model: "Seltos",
    price: "₹12,35,000",
    fuel: "Petrol",
    seats: 5,
    year: 2022,
    mileage: "17 kmpl",
    description: "A feature-rich SUV with great performance and style.",
    image: "/images/seltos.jpg",
    link: "https://www.kia.com/in/our-vehicles/seltos/showroom.html"
  },
  {
    id: 7,
    brand: "Honda",
    model: "City",
    price: "₹12,08,000",
    fuel: "Petrol",
    seats: 5,
    year: 2023,
    mileage: "18.4 kmpl",
    description: "A classy sedan offering comfort, power, and legacy.",
    image: "/images/city.jpg",
    link: "https://www.hondacarindia.com/honda-city"
  },
  {
    id: 8,
    brand: "MG",
    model: "ZS EV",
    price: "₹18,98,000",
    fuel: "Electric",
    seats: 5,
    year: 2023,
    mileage: "461 km/full charge",
    description: "An electric SUV with futuristic design and great range.",
    image: "/images/zs-ev.jpg",
    link: "https://www.mgmotor.co.in/electric-vehicle/zs-ev"
  },
  {
    id: 9,
    brand: "Skoda",
    model: "Slavia",
    price: "₹11,63,000",
    fuel: "Petrol",
    seats: 5,
    year: 2023,
    mileage: "19 kmpl",
    description: "Premium sedan from Skoda with a punchy engine.",
    image: "/images/slavia.jpg",
    link: "https://www.skoda-auto.co.in/models/slavia/slavia"
  },
  {
    id: 10,
    brand: "Renault",
    model: "Kiger",
    price: "₹6,49,000",
    fuel: "Petrol",
    seats: 5,
    year: 2022,
    mileage: "20 kmpl",
    description: "A compact SUV for city and occasional adventures.",
    image: "/images/kiger.webp",
    link: "https://www.renault.co.in/cars/kiger.html"
  },
  {
    id: 11,
    brand: "Maruti Suzuki",
    model: "Baleno",
    price: "₹6,61,000",
    fuel: "Petrol",
    seats: 5,
    year: 2022,
    mileage: "22 kmpl",
    description: "A stylish and efficient premium hatchback.",
    image: "/images/baleno.jpg",
    link: "https://www.nexaexperience.com/baleno"
  },
  {
    id: 12,
    brand: "Tata",
    model: "Harrier",
    price: "₹15,49,000",
    fuel: "Diesel",
    seats: 5,
    year: 2023,
    mileage: "16 kmpl",
    description: "A bold SUV with powerful presence and safety.",
    image: "/images/harrier.jpg",
    link: "https://cars.tatamotors.com/suv/harrier"
  },
  {
    id: 13,
    brand: "Hyundai",
    model: "Venue",
    price: "₹7,94,000",
    fuel: "Petrol",
    seats: 5,
    year: 2023,
    mileage: "18.2 kmpl",
    description: "A well-priced SUV packed with tech and comfort.",
    image: "/images/venue.jpg",
    link: "https://www.hyundai.com/in/en/find-a-car/venue/highlights"
  },
  {
    id: 14,
    brand: "Kia",
    model: "Carens",
    price: "₹10,45,000",
    fuel: "Diesel",
    seats: 7,
    year: 2023,
    mileage: "17.5 kmpl",
    description: "Family MPV with flexible seating and premium features.",
    image: "/images/carens.jpg",
    link: "https://www.kia.com/in/our-vehicles/carens/showroom.html"
  },
  {
    id: 15,
    brand: "Toyota",
    model: "Innova Crysta",
    price: "₹19,99,000",
    fuel: "Diesel",
    seats: 7,
    year: 2023,
    mileage: "15 kmpl",
    description: "India's most reliable MPV for long journeys and families.",
    image: "/images/innova-crysta.jpg",
    link: "https://www.toyotabharat.com/showroom/innova-crysta/"
  }
];

export { cars };
